import { useEffect, useState } from "react";
import "./app.css";
import { buildInitialTiptoeState, nextTiptoeCard, parseJson, pickClassicPrompt, supabase } from "./config.js";
import { CreateRoomScreen, HomeScreen, JoinRoomScreen, LobbyScreen } from "./components.jsx";
import { ClassicGameScreen, TiptoeGameScreen } from "./games.jsx";

export default function App() {
  const [view,setView]=useState("home"); const [selectedGame,setSelectedGame]=useState("truth_dare"); const [joinCode,setJoinCode]=useState(null); const [roomCode,setRoomCode]=useState(null); const [me,setMe]=useState(null); const [room,setRoom]=useState(null); const [players,setPlayers]=useState([]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const linkCode=params.get("join")?.toUpperCase().slice(0,4);if(linkCode){setJoinCode(linkCode);setView("join");return;}try{const saved=localStorage.getItem("afterparty_session_v2");if(saved){const parsed=JSON.parse(saved);if(parsed.roomCode&&parsed.me){setRoomCode(parsed.roomCode);setMe(parsed.me)}}}catch{}},[]);
  useEffect(()=>{if(!roomCode||!me)return;try{localStorage.setItem("afterparty_session_v2",JSON.stringify({roomCode,me}))}catch{}},[roomCode,me]);
  useEffect(()=>{if(!roomCode)return undefined;let active=true;async function load(){const [{data:r},{data:p}]=await Promise.all([supabase.from("rooms").select("*").eq("code",roomCode).maybeSingle(),supabase.from("players").select("*").eq("room_code",roomCode).order("join_order",{ascending:true})]);if(!active)return;if(!r){leave();return}setRoom(r);setPlayers(p||[]);setView(r.status==="playing"?"game":"lobby")}load();const channel=supabase.channel(`afterparty-room-${roomCode}`).on("postgres_changes",{event:"*",schema:"public",table:"rooms",filter:`code=eq.${roomCode}`},(payload)=>{if(payload.eventType!=="DELETE"){setRoom(payload.new);setView(payload.new.status==="playing"?"game":"lobby")}}).on("postgres_changes",{event:"*",schema:"public",table:"players",filter:`room_code=eq.${roomCode}`},()=>{supabase.from("players").select("*").eq("room_code",roomCode).order("join_order",{ascending:true}).then(({data})=>setPlayers(data||[]))}).subscribe();return()=>{active=false;supabase.removeChannel(channel)}},[roomCode]);
  const created=(code,player)=>{setMe(player);setRoomCode(code)}; const joined=(code,player)=>{setMe(player);setRoomCode(code);window.history.replaceState({},"",window.location.pathname)};
  async function start(setup){if(!room)return;if(room.game_mode==="tiptoe"){const state=buildInitialTiptoeState(setup,players);await supabase.from("rooms").update({status:"playing",current_player_index:0,current_type:"tiptoe",current_prompt:JSON.stringify(state)}).eq("code",roomCode);return}await supabase.from("rooms").update({status:"playing",current_player_index:0,current_type:null,current_prompt:null}).eq("code",roomCode)}
  async function classic(action,kind){if(!room)return;if(action==="draw"){await supabase.from("rooms").update({current_prompt:pickClassicPrompt(room,kind),current_type:kind}).eq("code",roomCode)}else if(action==="next"){const next=(room.current_player_index+1)%Math.max(players.length,1);await supabase.from("rooms").update({current_prompt:null,current_type:null,current_player_index:next}).eq("code",roomCode)}}
  async function tiptoe(action,value){const state=parseJson(room?.current_prompt,{});if(!state?.__tiptoe)return;let next={...state};if(action==="start_round"){next.phase="active";next.endsAt=Date.now()+(state.roundSeconds||60)*1000}else if(action==="score"){const scores=[...(state.scores||[0,0])];scores[state.activeTeam||0]=Math.max(0,(scores[state.activeTeam||0]||0)+Number(value||0));next=nextTiptoeCard({...state,scores,lastDelta:Number(value||0)});if(scores[0]>=state.scoreToWin||scores[1]>=state.scoreToWin)next.phase="ended"}else if(action==="time"){next.phase="summary";next.endsAt=null}else if(action==="next_round"){const activeTeam=(state.activeTeam||0)===0?1:0;const teamPlayers=players.filter((_,i)=>i%2===activeTeam);const teamRound=Math.floor((state.round||1)/2);next.activeTeam=activeTeam;next.round=(state.round||1)+1;next.phase="ready";next.guesserId=teamPlayers[teamRound%Math.max(teamPlayers.length,1)]?.id||teamPlayers[0]?.id||null;next=nextTiptoeCard(next)}else if(action==="rematch"){next=buildInitialTiptoeState({topicPacks:state.topicPacks,roundSeconds:state.roundSeconds,scoreToWin:state.scoreToWin},players)}await supabase.from("rooms").update({current_prompt:JSON.stringify(next),current_type:"tiptoe"}).eq("code",roomCode)}
  function leave(){setView("home");setJoinCode(null);setRoomCode(null);setRoom(null);setPlayers([]);setMe(null);try{localStorage.removeItem("afterparty_session_v2")}catch{}}
  if(view==="home")return <HomeScreen initialGame={selectedGame} onCreate={(game)=>{setSelectedGame(game);setView("create")}} onJoin={(code)=>{setJoinCode(code);setView("join")}}/>;
  if(view==="create")return <CreateRoomScreen initialGame={selectedGame} onRoomCreated={created} onBack={()=>setView("home")}/>;
  if(view==="join")return <JoinRoomScreen code={joinCode} onJoined={joined} onBack={()=>{setView("home");window.history.replaceState({},"",window.location.pathname)}}/>;
  if(view==="lobby"&&room&&me)return <LobbyScreen room={room} players={players} me={me} onStart={start} onLeave={leave}/>;
  if(view==="game"&&room&&me)return room.game_mode==="tiptoe"?<TiptoeGameScreen room={room} players={players} me={me} onAction={tiptoe}/>:<ClassicGameScreen room={room} players={players} me={me} onAction={classic}/>;
  return <main className="app-shell loading-shell">Loading Afterparty…</main>;
}
