import { useEffect, useState } from "react";
import { CONTENT, DISPLAY_OPTIONS, GAME_OPTIONS, TOPIC_PACKS, VIBE_IDS, categoryInfo, gameInfo, normalizeName, randomCode, remoteDisplay, setupFromRoom, supabase } from "./config.js";

export function AppIcon({ type, size = 48, color = "currentColor" }) {
  if (type === "question") return <div aria-hidden="true" style={{ fontSize: size, fontWeight: 900, lineHeight: 1, color }}>?</div>;
  if (type === "tiptoe") return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 64 64" fill="none"><ellipse cx="22" cy="34" rx="9" ry="15" transform="rotate(15 22 34)" stroke={color} strokeWidth="4"/><circle cx="14" cy="16" r="3.6" fill={color}/><circle cx="20" cy="12" r="3.3" fill={color}/><circle cx="26" cy="12" r="3" fill={color}/><circle cx="31" cy="15" r="2.7" fill={color}/><ellipse cx="43" cy="37" rx="8" ry="13" transform="rotate(-18 43 37)" stroke={color} strokeWidth="4"/><circle cx="50" cy="21" r="3.2" fill={color}/><circle cx="45" cy="17" r="3" fill={color}/><circle cx="40" cy="17" r="2.8" fill={color}/><circle cx="36" cy="20" r="2.5" fill={color}/></svg>;
  if (type === "truth_dare") return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 64 64" fill="none"><path d="M8 12h28a8 8 0 0 1 8 8v12a8 8 0 0 1-8 8H22l-10 10v-10H8a8 8 0 0 1-8-8V20a8 8 0 0 1 8-8Z" stroke={color} strokeWidth="4"/><path d="m42 22 14-8-5 13h8L43 49l5-15h-8l2-12Z" fill={color}/></svg>;
  const glyphs = { leaf: "❧", bolt: "ϟ", heart: "♥", chili: "◒", crown: "♛" };
  return <div aria-hidden="true" style={{ fontSize: size, fontWeight: 900, lineHeight: 1, color }}>{glyphs[type] || "✦"}</div>;
}

export function Button({ children, onClick, variant = "solid", accent = "#ff4f9a", disabled = false, className = "" }) {
  return <button type="button" onClick={disabled ? undefined : onClick} disabled={disabled} className={`button button--${variant} ${className}`} style={{ "--accent": accent }}>{children}</button>;
}

function TextField({ value, onChange, placeholder, maxLength = 40, onEnter, autoFocus = false, center = false }) {
  return <input autoFocus={autoFocus} value={value} maxLength={maxLength} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => e.key === "Enter" && onEnter?.()} placeholder={placeholder} className={`text-field ${center ? "text-field--center" : ""}`}/>;
}

export function Logo({ compact = false }) { return <div className={`brand ${compact ? "brand--compact" : ""}`} aria-label="Afterparty"><span>After</span><em>party</em><span className="brand-spark" aria-hidden="true">✦</span></div>; }

function OptionCard({ active, accent, title, subtitle, icon, onClick, compact = false }) {
  return <button type="button" className={`option-card ${compact ? "option-card--compact" : ""} ${active ? "option-card--active" : ""}`} style={{ "--accent": accent }} aria-pressed={active} onClick={onClick}>{icon ? <div className="option-card-icon">{icon}</div> : null}<strong>{title}</strong>{subtitle ? <span>{subtitle}</span> : null}</button>;
}

export function HomeScreen({ initialGame = "truth_dare", onCreate, onJoin }) {
  const [selectedGame, setSelectedGame] = useState(initialGame);
  const [joinOpen, setJoinOpen] = useState(false);
  const [joinCode, setJoinCode] = useState("");
  const selected = gameInfo(selectedGame);
  return <main className="app-shell landing-shell">
    <section className="landing-hero"><div className="landing-copy"><div className="eyebrow">AFTER HOURS · YOUR RULES · YOUR ROOM</div><Logo/><h1>Pick the energy.<br/>We’ll keep the party moving.</h1><p>One room. Three games. Play on phones, pass one device around, or put the action on your Fire TV.</p></div><div className="hero-orbit" style={{ "--accent": selected.accent }} aria-hidden="true"><div className="orbit-glow"/><div className="orbit-core"><AppIcon type={selected.icon} size={88} color={selected.accent}/></div><div className="orbit-label">{selected.label}</div></div></section>
    <section className="game-picker"><div className="section-heading-row"><div><div className="eyebrow">GAME</div><h2>What are we playing?</h2></div></div><div className="game-grid">{GAME_OPTIONS.map((game) => <button type="button" key={game.id} aria-pressed={selectedGame === game.id} onClick={() => setSelectedGame(game.id)} className={`game-card ${selectedGame === game.id ? "game-card--active" : ""}`} style={{ "--accent": game.accent }}><div className="game-card-icon"><AppIcon type={game.icon} size={58} color={game.accent}/></div><div className="game-card-copy"><span>{game.kicker}</span><strong>{game.label}</strong><p>{game.blurb}</p></div>{game.id === "tiptoe" ? <span className="new-badge">TEAM PLAY</span> : null}</button>)}</div></section>
    <section className="landing-actions">{!joinOpen ? <><Button accent={selected.accent} onClick={() => onCreate(selectedGame)}>Host {selected.label}</Button><Button variant="outline" accent="#a89cc8" onClick={() => setJoinOpen(true)}>Join an existing room</Button></> : <div className="join-panel"><div className="eyebrow">JOIN A ROOM</div><TextField value={joinCode} onChange={(v) => setJoinCode(v.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 4))} placeholder="ROOM CODE" maxLength={4} center autoFocus onEnter={() => joinCode.length === 4 && onJoin(joinCode)}/><div className="button-row"><Button accent="#8cff4f" disabled={joinCode.length !== 4} onClick={() => onJoin(joinCode)}>Continue</Button><Button variant="ghost" onClick={() => setJoinOpen(false)}>Back</Button></div></div>}</section>
  </main>;
}

export function CreateRoomScreen({ initialGame, onRoomCreated, onBack }) {
  const [name, setName] = useState(""); const [gameMode, setGameMode] = useState(initialGame || "truth_dare"); const [category, setCategory] = useState("mild");
  const [displayMode, setDisplayMode] = useState("tv_phones"); const [playFormat, setPlayFormat] = useState(initialGame === "tiptoe" ? "teams" : "individual");
  const [topicPacks, setTopicPacks] = useState(["everyday"]); const [roundSeconds, setRoundSeconds] = useState(60); const [scoreToWin, setScoreToWin] = useState(15); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (gameMode === "tiptoe") setPlayFormat("teams"); }, [gameMode]);
  const activeGame = gameInfo(gameMode); const accent = gameMode === "tiptoe" ? activeGame.accent : categoryInfo(category).accent;
  const togglePack = (pack) => setTopicPacks((current) => current.includes(pack) ? (current.length === 1 ? current : current.filter((item) => item !== pack)) : [...current, pack]);
  async function handleCreate() { const cleanName = normalizeName(name); if (!cleanName || busy) return; setBusy(true); setError(""); try { let code = randomCode(); for (let attempt = 0; attempt < 6; attempt += 1) { const { data } = await supabase.from("rooms").select("code").eq("code", code).maybeSingle(); if (!data) break; code = randomCode(); } const setup = { __setup: 1, displayMode, playFormat: gameMode === "tiptoe" ? "teams" : playFormat, topicPacks: gameMode === "tiptoe" ? topicPacks : [], roundSeconds, scoreToWin }; const { error: roomError } = await supabase.from("rooms").insert({ code, game_mode: gameMode, category: gameMode === "tiptoe" ? topicPacks[0] : category, status: "lobby", current_player_index: 0, current_type: "setup", current_prompt: JSON.stringify(setup) }); if (roomError) throw roomError; const { data: player, error: playerError } = await supabase.from("players").insert({ room_code: code, name: cleanName, join_order: 0 }).select().single(); if (playerError) throw playerError; onRoomCreated(code, player); } catch (e) { console.error(e); setError("Couldn’t create the room. Check your connection and try again."); setBusy(false); } }
  return <main className="app-shell setup-shell"><button type="button" onClick={onBack} className="back-link">← Back</button><header className="setup-header"><Logo compact/><div><div className="eyebrow">HOST SETUP</div><h1>Build the room</h1><p>Choose the game, how everyone is playing, then set the content.</p></div></header>
    <section className="setup-section"><div className="setup-section-title"><span>1</span><div><strong>Game</strong><small>What are we playing?</small></div></div><div className="setup-game-row">{GAME_OPTIONS.map((game) => <OptionCard key={game.id} active={gameMode === game.id} accent={game.accent} title={game.label} subtitle={game.kicker} icon={<AppIcon type={game.icon} size={34} color={game.accent}/>} compact onClick={() => setGameMode(game.id)}/>)}</div></section>
    <section className="setup-section"><div className="setup-section-title"><span>2</span><div><strong>Host name</strong><small>This name appears in the room</small></div></div><TextField value={name} onChange={setName} placeholder="Nikki Caruthers" maxLength={40} autoFocus/></section>
    <section className="setup-section"><div className="setup-section-title"><span>3</span><div><strong>Display</strong><small>Where should the game live?</small></div></div><div className="display-grid">{DISPLAY_OPTIONS.map((o) => <OptionCard key={o.id} active={displayMode === o.id} accent="#8A67FF" title={o.label} subtitle={o.short} compact onClick={() => setDisplayMode(o.id)}/>)}</div>{remoteDisplay(displayMode) ? <div className="inline-note">QR + 4-letter room code will appear in the lobby.</div> : null}</section>
    {gameMode !== "tiptoe" ? <><section className="setup-section"><div className="setup-section-title"><span>4</span><div><strong>Play format</strong><small>Couples / Flirty is a vibe; Teams is the play format</small></div></div><div className="two-up"><OptionCard active={playFormat === "individual"} accent="#5b8cff" title="Individual" subtitle="Everyone plays for themselves" onClick={() => setPlayFormat("individual")}/><OptionCard active={playFormat === "teams"} accent="#8cff4f" title="Teams" subtitle="Split the room into sides" onClick={() => setPlayFormat("teams")}/></div></section><section className="setup-section"><div className="setup-section-title"><span>5</span><div><strong>Vibe</strong><small>{gameMode === "questions" ? "Questions" : "Truth or Dare"} uses all five vibe categories</small></div></div><div className="vibe-grid">{VIBE_IDS.map((id) => { const meta = categoryInfo(id); return <button type="button" key={id} className={`vibe-card ${category === id ? "vibe-card--active" : ""}`} style={{ "--accent": meta.accent }} onClick={() => setCategory(id)} aria-pressed={category === id}><div className="vibe-icon"><AppIcon type={meta.icon} size={34} color={meta.accent}/></div><strong>{meta.label}</strong><span>{meta.short}</span></button>; })}</div></section></> : <><section className="setup-section"><div className="setup-section-title"><span>4</span><div><strong>Teams</strong><small>Tiptoe is built for team play</small></div></div><div className="inline-note inline-note--green">Players auto-balance into Team Neon and Team Glow.</div></section><section className="setup-section"><div className="setup-section-title"><span>5</span><div><strong>Topic packs</strong><small>Choose one or more</small></div></div><div className="topic-grid">{TOPIC_PACKS.map(([id,label,icon]) => <OptionCard key={id} active={topicPacks.includes(id)} accent={id === "after_dark" ? "#ff4f9a" : "#8cff4f"} title={label} icon={<span className="topic-symbol">{icon}</span>} compact onClick={() => togglePack(id)}/>)}</div></section><section className="setup-section"><div className="setup-section-title"><span>6</span><div><strong>Match</strong><small>Timer and score target</small></div></div><div className="match-grid"><label><span>Round timer</span><select value={roundSeconds} onChange={(e) => setRoundSeconds(Number(e.target.value))}><option value={30}>30 sec</option><option value={45}>45 sec</option><option value={60}>60 sec</option><option value={90}>90 sec</option></select></label><label><span>Score to win</span><select value={scoreToWin} onChange={(e) => setScoreToWin(Number(e.target.value))}><option value={10}>10 points</option><option value={15}>15 points</option><option value={25}>25 points</option><option value={40}>40 points</option></select></label></div></section></>}
    {error ? <div className="error-banner">{error}</div> : null}<div className="sticky-action"><div><span>{activeGame.label}</span><small>{DISPLAY_OPTIONS.find((o) => o.id === displayMode)?.label}</small></div><Button accent={accent} disabled={!normalizeName(name) || busy} onClick={handleCreate}>{busy ? "Creating…" : "Create room"}</Button></div></main>;
}

export function JoinRoomScreen({ code, onJoined, onBack }) {
  const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function handleJoin(){const clean=normalizeName(name);if(!clean||busy)return;setBusy(true);setError("");try{const {data:room,error:roomError}=await supabase.from("rooms").select("code,status").eq("code",code).maybeSingle();if(roomError||!room){setError("Room not found. Double-check the code.");setBusy(false);return;}const {data:existing}=await supabase.from("players").select("id").eq("room_code",code);const {data:player,error:playerError}=await supabase.from("players").insert({room_code:code,name:clean,join_order:existing?.length||0}).select().single();if(playerError)throw playerError;onJoined(code,player);}catch(e){console.error(e);setError("Something went wrong joining the room.");setBusy(false);}}
  return <main className="app-shell join-shell"><button type="button" onClick={onBack} className="back-link">← Back</button><div className="join-card"><Logo compact/><div className="eyebrow">JOIN ROOM {code}</div><h1>Who’s playing?</h1><p>Enter your name. The room already knows the game and settings.</p><TextField value={name} onChange={setName} placeholder="Your name" autoFocus maxLength={40} onEnter={handleJoin}/>{error?<div className="error-banner">{error}</div>:null}<Button accent="#8cff4f" disabled={!normalizeName(name)||busy} onClick={handleJoin}>{busy?"Joining…":"Join room"}</Button></div></main>;
}

function QrJoin({roomCode}){const joinUrl=`${window.location.origin}/?join=${roomCode}&role=phone`;const src=`https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=8&data=${encodeURIComponent(joinUrl)}`;return <div className="qr-card"><div className="qr-copy"><div className="eyebrow">JOIN FROM A PHONE</div><h3>Scan to enter room {roomCode}</h3><p>Camera → scan → enter your name. The room code is already filled in.</p><button type="button" className="copy-link" onClick={()=>navigator.clipboard?.writeText(joinUrl)}>Copy join link</button></div><div className="qr-frame"><img src={src} alt={`QR code to join room ${roomCode}`}/></div></div>}

export function LobbyScreen({room,players,me,onStart,onLeave}){const isHost=players[0]?.id===me?.id;const game=gameInfo(room.game_mode);const setup=setupFromRoom(room);const vibe=room.game_mode==="tiptoe"?null:categoryInfo(room.category);const display=DISPLAY_OPTIONS.find((o)=>o.id===setup.displayMode)||DISPLAY_OPTIONS[1];const topicLabel=room.game_mode==="tiptoe"?setup.topicPacks.map((id)=>TOPIC_PACKS.find(([pack])=>pack===id)?.[1]||id).join(" · "):vibe?.label;return <main className="app-shell lobby-shell"><div className="lobby-topbar"><Logo compact/><button type="button" onClick={onLeave} className="back-link">Leave room</button></div><section className="lobby-hero" style={{"--accent":game.accent}}><div><div className="eyebrow">ROOM CODE</div><div className="room-code">{room.code}</div><div className="lobby-pills"><span>{game.label}</span><span>{topicLabel}</span><span>{display.label}</span>{setup.playFormat?<span>{setup.playFormat==="teams"?"Teams":"Individual"}</span>:null}</div></div><div className="lobby-game-icon"><AppIcon type={game.icon} size={72} color={game.accent}/></div></section>{remoteDisplay(setup.displayMode)?<QrJoin roomCode={room.code}/>:<div className="local-mode-card"><strong>{display.label}</strong><span>No phone join required for this display mode.</span></div>}<section className="players-card"><div className="section-heading-row"><div><div className="eyebrow">PLAYERS</div><h2>{players.length} in the room</h2></div>{room.game_mode==="tiptoe"?<span className="step-chip">Auto-balanced teams</span>:null}</div><div className="player-grid">{players.map((p,i)=><div key={p.id} className="player-chip"><span className="avatar" style={{"--accent":room.game_mode==="tiptoe"?(i%2===0?"#ff4f9a":"#5b8cff"):game.accent}}>{p.name.slice(0,2).toUpperCase()}</span><div><strong>{p.name}</strong><small>{i===0?"Host":room.game_mode==="tiptoe"?`Team ${i%2===0?"Neon":"Glow"}`:"Player"}</small></div>{p.id===me.id?<span className="you-chip">YOU</span>:null}</div>)}</div></section><div className="sticky-action sticky-action--lobby"><div><span>{isHost?"Ready when the room is.":"Waiting for the host"}</span><small>{room.game_mode==="tiptoe"?`${setup.roundSeconds}s rounds · first to ${setup.scoreToWin}`:topicLabel}</small></div>{isHost?<Button accent={game.accent} disabled={players.length<2} onClick={()=>onStart(setup)}>{players.length<2?"Waiting for another player…":`Start ${game.label}`}</Button>:<div className="waiting-dot">●</div>}</div></main>}
