import { useEffect, useState } from "react";
import { TOPIC_PACKS, categoryInfo, parseJson } from "./config.js";
import { AppIcon, Button, Logo } from "./components.jsx";

export function ClassicGameScreen({ room, players, me, onAction }) {
  const category = categoryInfo(room.category); const currentPlayer = players[room.current_player_index % Math.max(players.length,1)]; const isMyTurn=currentPlayer?.id===me?.id; const hasPrompt=room.current_type!=="setup"&&Boolean(room.current_prompt);
  return <main className="app-shell game-shell"><div className="game-topbar"><Logo compact/><div className="lobby-pills"><span>{room.game_mode==="questions"?"Questions":"Truth or Dare"}</span><span style={{color:category.accent}}>{category.label}</span></div></div><section className="turn-header"><div className="eyebrow">{isMyTurn?"YOUR TURN":"CURRENT TURN"}</div><h1 style={{color:category.accent}}>{currentPlayer?.name||"Player"}</h1></section><section className={`prompt-card ${hasPrompt?"prompt-card--live":""}`} style={{"--accent":category.accent}}>{hasPrompt?<><div className="eyebrow" style={{color:category.accent}}>{room.current_type?.toUpperCase()}</div><p>{room.current_prompt}</p></>:<div className="prompt-empty">{isMyTurn?(room.game_mode==="questions"?"Draw your question.":"Truth or dare?"):`Waiting for ${currentPlayer?.name||"the player"}…`}</div>}</section><section className="game-actions">{isMyTurn&&!hasPrompt&&room.game_mode==="truth_dare"?<div className="two-up"><Button accent="#34D6B0" onClick={()=>onAction("draw","truth")}>Truth</Button><Button accent="#FF5A4E" onClick={()=>onAction("draw","dare")}>Dare</Button></div>:null}{isMyTurn&&!hasPrompt&&room.game_mode==="questions"?<Button accent={category.accent} onClick={()=>onAction("draw","question")}>Draw question</Button>:null}{isMyTurn&&hasPrompt?<Button accent={category.accent} onClick={()=>onAction("next")}>Done · Next player</Button>:null}</section></main>;
}

export function TiptoeGameScreen({ room, players, me, onAction }) {
  const state=parseJson(room.current_prompt,{}); const [now,setNow]=useState(Date.now()); const isHost=players[0]?.id===me?.id; const isGuesser=state.guesserId===me?.id; const myIndex=players.findIndex((p)=>p.id===me?.id); const myTeam=myIndex>=0?myIndex%2:null; const activeTeam=state.activeTeam||0; const activeTeamPlayers=players.filter((_,i)=>i%2===activeTeam); const activeGuesser=players.find((p)=>p.id===state.guesserId); const canScore=state.phase==="active"&&(isHost||(myTeam===activeTeam&&!isGuesser));
  useEffect(()=>{if(state.phase!=="active"||!state.endsAt)return undefined;const id=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(id)},[state.phase,state.endsAt]);
  const remainingMs=state.phase==="active"&&state.endsAt?Math.max(0,state.endsAt-now):(state.roundSeconds||60)*1000; const remaining=Math.ceil(remainingMs/1000);
  useEffect(()=>{if(isHost&&state.phase==="active"&&state.endsAt&&remainingMs<=0)onAction("time")},[isHost,state.phase,state.endsAt,remainingMs,onAction]);
  const winner=state.scores?.[0]>=state.scoreToWin?0:state.scores?.[1]>=state.scoreToWin?1:null; const teamName=activeTeam===0?"Team Neon":"Team Glow"; const teamAccent=activeTeam===0?"#ff4f9a":"#5b8cff";
  return <main className="app-shell tiptoe-shell" style={{"--team-accent":teamAccent}}><div className="tiptoe-scorebar"><div><span>TEAM NEON</span><strong>{state.scores?.[0]||0}</strong></div><div className="tiptoe-mark"><AppIcon type="tiptoe" size={40} color="#8cff4f"/><span>TIPTOE</span><small>ROUND {state.round||1}</small></div><div><strong>{state.scores?.[1]||0}</strong><span>TEAM GLOW</span></div></div>
    {winner!==null||state.phase==="ended"?<section className="winner-card"><div className="eyebrow">MATCH WINNER</div><h1>{winner===0?"Team Neon":"Team Glow"}</h1><p>Final score {state.scores?.[0]||0} – {state.scores?.[1]||0}</p>{isHost?<Button accent="#8cff4f" onClick={()=>onAction("rematch")}>Rematch</Button>:null}</section>:state.phase==="ready"?<section className="ready-card"><div className="eyebrow">{teamName.toUpperCase()} IS UP</div><h1>{activeGuesser?.name||activeTeamPlayers[0]?.name||"Guesser"} is guessing</h1><p>{activeGuesser?.name||"Guesser"}: turn away from the shared screen. Everyone else gives clues without saying the forbidden words.</p>{isHost?<Button accent={teamAccent} onClick={()=>onAction("start_round")}>Start {state.roundSeconds||60}-second round</Button>:<div className="waiting-dot">●</div>}</section>:state.phase==="summary"?<section className="ready-card"><div className="eyebrow">ROUND COMPLETE</div><h1>{teamName}</h1><p>Score: {state.scores?.[activeTeam]||0}. Next up: {activeTeam===0?"Team Glow":"Team Neon"}.</p>{isHost?<Button accent={activeTeam===0?"#5b8cff":"#ff4f9a"} onClick={()=>onAction("next_round")}>Next team</Button>:null}</section>:<><section className="tiptoe-round-head"><div><div className="eyebrow">{teamName.toUpperCase()}</div><h2>{activeGuesser?.name||"Guesser"} is guessing</h2></div><div className={`countdown ${remaining<=10?"countdown--urgent":""}`}>{String(remaining).padStart(2,"0")}</div></section><section className={`tiptoe-card ${isGuesser?"tiptoe-card--hidden":""}`}>{isGuesser?<div className="guesser-cover"><AppIcon type="tiptoe" size={74} color={teamAccent}/><div className="eyebrow">DON’T PEEK</div><h1>Listen to your team.</h1><p>The target is hidden on your device while you’re guessing.</p></div>:<><div className="eyebrow">TARGET</div><h1>{state.card?.target||"No card"}</h1><div className="forbidden-box"><span>DON’T SAY</span><div>{(state.card?.forbidden||[]).map((word)=><b key={word}>{word}</b>)}</div></div><small>{TOPIC_PACKS.find(([id])=>id===state.card?.pack)?.[1]||state.card?.pack}</small></>}</section>{canScore?<section className="tiptoe-actions"><Button accent="#34D6B0" onClick={()=>onAction("score",1)}>✓ Correct +1</Button><Button variant="outline" accent="#a89cc8" onClick={()=>onAction("score",0)}>Pass</Button><Button variant="outline" accent="#FF5A4E" onClick={()=>onAction("score",-1)}>Forbidden −1</Button></section>:<div className="spectator-note">{isGuesser?"Your team controls the card.":"Scoring controls are on the active team / host device."}</div>}</>}
  </main>;
}
